import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header>
                    <nav>
                        <Link href="#" title="homepage">
                            Home
                        </Link>
                        <Link href="#" title="portfolio">
                            Portfolio
                        </Link>
                        <Link href="#" title="about me">
                            About me
                        </Link>
                        <Link href="#" title="contact">
                            Contact
                        </Link>
                    </nav>
                </header>
                <main>{children}</main>
                <footer>
                    🍪 &copy; Accepted Cookies {new Date().getFullYear()}
                </footer>
            </body>
        </html>
    );
}
