import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";
import { Mainmenu } from "@/components/main-menu";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Accepted Cookies - Freelance Sr. Fullstack developer",
    description: "Generated by create next app",
    icons: {
        icon: "/favicon/favicon.ico",
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="flex flex-row items-center justify-between sticky top-0 py-4 px-8">
                    <Link href="/">
                        <Image
                            alt="Accepted Cookies logo"
                            title="Accepted Cookies - fullstack development"
                            src="/images/accepted-cookies-logo.png"
                            width={72}
                            height={72}
                        />
                    </Link>

                    <Mainmenu />
                </header>
                <main className="min-h-full">{children}</main>
                <footer>
                    🍪 &copy; Accepted Cookies {new Date().getFullYear()}
                </footer>
            </body>
        </html>
    );
}
